version: '2'

services:
  server:
    build: .
    container_name: server
    command: npm run debug
    environment:      
      NODE_ENV: development
    volumes:
      - ./src:/usr/app/src
    ports:
      - "9998:80"
      - "5998:5858"