version: '2'

services:
  api:
    build: .
    command: npm run debug
    environment:      
      NODE_ENV: development
    volumes:
      - ./src:/usr/app/src
    ports:
      - "9999:80"
      - "5999:5858"